 export {default as Hero} from "./Hero"
 export {default as Navder} from "./Navber"
 export {default as Footer} from "./Footer.jsx"
 export {default as Memory} from "./Memory.jsx"
 export {default as Explor} from "./Explor.jsx"
 export {default as Brand} from "./Brand"
 export {default as Pricings} from "./Pricings"